name: bepoo
description: BePoo it's BeReal like social media app about pooping
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.4
  collection: ^1.17.1
  device_info_plus: ^9.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.8
  firebase_storage: ^11.2.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^2.0.7
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  geolocator: ^10.0.1
  get_it: ^7.6.0
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  image_picker: ^1.0.1
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  permission_handler: ^11.0.0
  pull_to_refresh: ^2.0.0
  rxdart: ^0.27.7
  sign_in_with_apple: ^5.0.0
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  uuid: ^4.0.0

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icons/
    - assets/sign_in_icons/

spider:
  generate_tests: true
  no_comments: true
  export: true
  use_part_of: true
  use_references_list: false
  package: resources
  groups:
    - path: assets/app_icons
      class_name: AppIcons
      types: [ .png ]

    - path: assets/sign_in_icons
      class_name: SignInIcons
      types: [ .svg ]