name: pooapp
description: PooApp it's BeReal like social media app about pooping
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.8.4
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.7
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get_it: ^7.6.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  permission_handler: ^10.4.3
  sign_in_with_apple: ^5.0.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icons/
    - assets/sign_in_icons/