// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMUQedp3zbVzh99gy4mpt_rS8n2peSVjY',
    appId: '1:636542386317:android:9da87e64f42f45a50162c4',
    messagingSenderId: '636542386317',
    projectId: 'pooapp-d70ed',
    storageBucket: 'pooapp-d70ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdmLwsli3XaC8rJmXspqs6PQGQB8tzbko',
    appId: '1:636542386317:ios:ec95b554044f92010162c4',
    messagingSenderId: '636542386317',
    projectId: 'pooapp-d70ed',
    storageBucket: 'pooapp-d70ed.appspot.com',
    iosClientId: '636542386317-a421hhbtckao42aeqsum0epvc6t4tluk.apps.googleusercontent.com',
    iosBundleId: 'com.piekarskipiotr.bepoo',
  );
}
